spring.application.name=learning
spring.datasource.url=jdbc:h2:file:/Users/utkarsh.nain/Downloads/learning/db
spring.datasource.username=test
spring.datasource.password=test123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
